# Generated by Django 5.2 on 2025-11-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='napr.: home, services, footer', max_length=64, unique=True, verbose_name='Section slug')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Site section',
                'verbose_name_plural': 'Site sections',
            },
        ),
        migrations.CreateModel(
            name='SiteSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='napr.: hero_title, hero_lead, hero_image', max_length=64, verbose_name='Slot slug')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=16, verbose_name='Content kind')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='dashboard.sitesection')),
            ],
            options={
                'verbose_name': 'Site slot',
                'verbose_name_plural': 'Site slots',
                'unique_together': {('section', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='EditableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='editable_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editable_images', to='accounting.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'company'), name='uniq_editableimage_key_company'), models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('key',), name='uniq_editableimage_key_global')],
            },
        ),
        migrations.CreateModel(
            name='EditableText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(blank=True, help_text='Автогенерируется из секции/слота, если выбран слот.', max_length=128, verbose_name='Key')),
                ('language', models.CharField(choices=[('sk', 'Slovak'), ('en', 'English'), ('ru', 'Russian')], default='sk', max_length=5, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title (optional)')),
                ('text', models.TextField(blank=True, verbose_name='Text / HTML')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editable_texts', to='accounting.company')),
                ('slot', models.ForeignKey(blank=True, limit_choices_to={'kind': 'text'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='dashboard.siteslot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'company'), name='uniq_editabletext_key_company'), models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('key',), name='uniq_editabletext_key_global')],
            },
        ),
    ]
