# Generated by Django 5.2 on 2025-11-03 08:37

import apps.contact_messages.crypto_fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', apps.contact_messages.crypto_fields.EncryptedEmailField(max_length=254)),
                ('email_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('service', models.CharField(choices=[('office_space', 'Office Space'), ('billboard', 'Billboard Advertising'), ('legal_address', 'Legal Address'), ('multiple', 'Multiple Services')], max_length=50)),
                ('message', apps.contact_messages.crypto_fields.EncryptedTextField(blank=True, null=True)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('consent_version', models.CharField(blank=True, max_length=20, null=True)),
                ('consent_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='contact_mes_status_c1618f_idx'), models.Index(fields=['service'], name='contact_mes_service_e19743_idx'), models.Index(fields=['created_at'], name='contact_mes_created_67b548_idx'), models.Index(fields=['email'], name='contact_mes_email_5e74b6_idx')],
            },
        ),
    ]
