# Generated by Django 5.2 on 2025-10-29 10:08

import apps.contact_messages.crypto_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=apps.contact_messages.crypto_fields.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=apps.contact_messages.crypto_fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
