# Generated by Django 5.2 on 2025-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_messages', '0002_alter_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
