# Generated by Django 5.2 on 2025-11-28 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('available', 'Volné'), ('reserved', 'Rezervováno'), ('occupied', 'Obsazeno'), ('hidden', 'Skryto/na servisu')], db_index=True, default='available', max_length=16)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, help_text='Rozmer (napr. 5x2 m)', max_length=100)),
                ('visibility', models.CharField(blank=True, help_text='Viditeľnosť alebo orientácia', max_length=255)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['property__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalAddressUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('available', 'Volné'), ('reserved', 'Rezervováno'), ('occupied', 'Obsazeno'), ('hidden', 'Skryto/na servisu')], db_index=True, default='available', max_length=16)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, help_text='Описание юридического адреса или особенностей')),
                ('price_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['property__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfficeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('available', 'Volné'), ('reserved', 'Rezervováno'), ('occupied', 'Obsazeno'), ('hidden', 'Skryto/na servisu')], db_index=True, default='available', max_length=16)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('floor', models.IntegerField(help_text='Číslo poschodia (napr. 0 = prízemie, 1 = prvé poschodie)')),
                ('unit_number', models.CharField(help_text='Číslo kancelárie alebo identifikátor', max_length=50)),
                ('area_sqm', models.FloatField(help_text='Rozloha v m²')),
                ('price_per_month', models.DecimalField(decimal_places=2, help_text='Cena za mesiac (€)', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('iframe', models.TextField(blank=True, help_text='HTML iframe z Google Maps pre túto jednotku')),
            ],
            options={
                'ordering': ['floor', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('available', 'Volné'), ('reserved', 'Rezervováno'), ('occupied', 'Obsazeno'), ('hidden', 'Skryto/na servisu')], db_index=True, default='available', max_length=16)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('list_details', models.JSONField(blank=True, default=list, help_text='Detaily pre zobrazenie v zozname', max_length=1044)),
                ('summary', models.CharField(blank=True, help_text='Krátky popis', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('iframe', models.TextField(blank=True, help_text='HTML iframe  Google Maps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillboardUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='billboard_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('billboard_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.billboardunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalAddressUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='legal_address_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('legal_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.legaladdressunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='office_unit_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('office_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.officeunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='officeunit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_units', to='properties.property'),
        ),
        migrations.AddField(
            model_name='legaladdressunit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_addresses', to='properties.property'),
        ),
        migrations.AddField(
            model_name='billboardunit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billboards', to='properties.property'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype'),
        ),
        migrations.AlterUniqueTogether(
            name='officeunit',
            unique_together={('property', 'floor', 'unit_number')},
        ),
    ]
