# Generated by Django 5.2 on 2025-11-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytype',
            name='icon_svg',
        ),
    ]
