# Generated by Django 5.2 on 2025-11-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeunit',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Plný URL na Google Maps embed (bez HTML)'),
        ),
        migrations.AddField(
            model_name='property',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Plný URL na Google Maps embed (bez HTML)'),
        ),
        migrations.AlterField(
            model_name='officeunit',
            name='iframe',
            field=models.TextField(blank=True, help_text='HTML iframe z Google Maps pre túto jednotku (legacy)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='iframe',
            field=models.TextField(blank=True, help_text='HTML iframe  Google Maps (legacy, už sa nepoužíva priamo)'),
        ),
    ]
