# Generated by Django 5.2 on 2025-11-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeunit',
            name='iframe',
            field=models.TextField(blank=True, help_text='HTML iframe z Google Maps pre túto jednotku'),
        ),
    ]
