# Generated by Django 5.2 on 2025-11-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_officeunit_iframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytype',
            name='type_id',
        ),
    ]
