# Generated by hand to extend map_embed_url length for long Google Maps embed links
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_officeunit_map_embed_url_property_map_embed_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officeunit",
            name="map_embed_url",
            field=models.URLField(
                max_length=1024,
                blank=True,
                help_text="Plný URL na Google Maps embed (bez HTML)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="map_embed_url",
            field=models.URLField(
                max_length=1024,
                blank=True,
                help_text="Plný URL na Google Maps embed (bez HTML)",
            ),
        ),
    ]
