# Generated by Django 5.2 on 2025-12-04 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_expand_map_embed_url_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='officeunit',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Vlastnosti a vybavenie kancelárie', related_name='office_units', to='properties.officefeature'),
        ),
    ]
