# Generated by Django 5.2 on 2025-10-31 10:14

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Напр.: hero.image, services.billboard.hero, about.gallery1', max_length=128, unique=True, verbose_name='Key')),
                ('language', models.CharField(choices=[('sk', 'Slovak'), ('en', 'English'), ('ru', 'Russian')], default='sk', max_length=5, verbose_name='Language')),
                ('image', models.ImageField(upload_to=dashboard.models.upload_to_images, verbose_name='Image')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Editable image',
                'verbose_name_plural': 'Editable images',
            },
        ),
        migrations.CreateModel(
            name='EditableText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Напр.: hero.title, footer.about, services.office.lead', max_length=128, unique=True, verbose_name='Key')),
                ('language', models.CharField(choices=[('sk', 'Slovak'), ('en', 'English'), ('ru', 'Russian')], default='sk', max_length=5, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title (optional)')),
                ('text', models.TextField(blank=True, verbose_name='Text / HTML')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Editable text',
                'verbose_name_plural': 'Editable texts',
            },
        ),
    ]
