# Generated by Django 5.2 on 2025-07-30 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(help_text='Číslo poschodia (napr. 0 = prízemie, 1 = prvé poschodie)')),
                ('unit_number', models.CharField(help_text='Číslo kancelárie alebo identifikátor', max_length=50)),
                ('area_sqm', models.FloatField(help_text='Rozloha v m²')),
                ('price_per_month', models.DecimalField(decimal_places=2, help_text='Cena za mesiac (€)', max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Voľné'), ('occupied', 'Obsadené')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['floor', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('list_details', models.JSONField(blank=True, default=list, help_text='Detaily pre zobrazenie v zozname')),
                ('summary', models.CharField(blank=True, help_text='Krátky popis', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('iframe', models.TextField(blank=True, help_text='HTML iframe  Google Maps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon_svg', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='office_unit_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('office_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.officeunit')),
            ],
        ),
        migrations.AddField(
            model_name='officeunit',
            name='property',
            field=models.ForeignKey(limit_choices_to={'type': 'office'}, on_delete=django.db.models.deletion.CASCADE, related_name='office_units', to='properties.property'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype'),
        ),
        migrations.AlterUniqueTogether(
            name='officeunit',
            unique_together={('property', 'floor', 'unit_number')},
        ),
    ]
