# Generated by Django 5.2 on 2025-05-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='summary',
            field=models.CharField(blank=True, help_text='Krátky popis', max_length=255),
        ),
    ]
