# Generated by Django 5.2 on 2025-05-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='iframe',
            field=models.TextField(blank=True, help_text='HTML iframe  Google Maps'),
        ),
    ]
