# Generated by Django 5.2 on 2025-07-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_officeunit_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='list_details',
            field=models.JSONField(blank=True, default=list, help_text='Detaily pre zobrazenie v zozname', max_length=1044),
        ),
    ]
