# Generated by Django 5.2 on 2025-10-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_list_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='busy_until',
            field=models.DateField(blank=True, help_text='Ak je nehnuteľnosť obsadená, do kedy?', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(blank=True, default='EUR', help_text='Mena ceny', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='free',
            field=models.BooleanField(blank=True, default=True, help_text='Je nehnuteľnosť voľná?', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena za prenájom (ak je relevantné)', max_digits=10, null=True),
        ),
    ]
