# Generated by Django 5.2 on 2025-05-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('office', 'Kancelária'), ('address', 'Sydlo'), ('billboard', 'Billboard')], max_length=20),
        ),
    ]
