# Generated by Django 5.2 on 2025-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='list_details',
            field=models.TextField(blank=True, help_text='Podrobnosti o nehnuteľnosti'),
        ),
    ]
