# Generated by Django 5.2 on 2025-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_list_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='list_details',
            field=models.JSONField(blank=True, default=list, help_text='Detaily pre zobrazenie v zozname'),
        ),
    ]
