# Generated by Django 5.2 on 2025-07-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_list_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(help_text='Číslo poschodia (napr. 0 = prízemie, 1 = prvé poschodie)')),
                ('unit_number', models.CharField(help_text='Číslo kancelárie alebo identifikátor', max_length=50)),
                ('area_sqm', models.FloatField(help_text='Rozloha v m²')),
                ('price_per_month', models.DecimalField(decimal_places=2, help_text='Cena za mesiac (€)', max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Voľné'), ('occupied', 'Obsadené')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('property', models.ForeignKey(limit_choices_to={'type': 'office'}, on_delete=django.db.models.deletion.CASCADE, related_name='office_units', to='properties.property')),
            ],
            options={
                'ordering': ['floor', 'unit_number'],
                'unique_together': {('property', 'floor', 'unit_number')},
            },
        ),
    ]
