# Generated by Django 5.2 on 2025-07-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_officeunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='office_unit_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('office_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.officeunit')),
            ],
        ),
    ]
