# Generated by Django 5.2 on 2025-07-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ico', models.CharField(blank=True, max_length=20, verbose_name='IČO')),
                ('dic', models.CharField(blank=True, max_length=20, verbose_name='DIČ')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informácie o firme',
                'verbose_name_plural': 'Informácie o firme',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='Agentúra Závodský', max_length=100)),
                ('about_description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_address', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontendTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('navbar_background', models.CharField(default='#ffffff', max_length=20)),
                ('body_background', models.CharField(default='#f9fafb', max_length=20)),
                ('footer_background', models.CharField(default='#f1f5f9', max_length=20)),
                ('text_color', models.CharField(default='#111827', max_length=20)),
                ('text_hover_color', models.CharField(default='#1e40af', max_length=20)),
                ('border_color', models.CharField(default='#d1d5db', max_length=20)),
                ('border_hover_color', models.CharField(default='#9ca3af', max_length=20)),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('primary_hover_color', models.CharField(default='#1d4ed8', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='Agentúra Závodský s.r.o.', max_length=100)),
                ('nav_services', models.CharField(default='Služby', max_length=50)),
                ('nav_why', models.CharField(default='Prečo práve my?', max_length=50)),
                ('nav_contact', models.CharField(default='Kontakt', max_length=50)),
                ('button_text', models.CharField(default='Zanechajte žiadosť', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, default='Kancelárske priestory, právne adresy a billboardy – všetko na jednom mieste.', null=True)),
                ('button_text', models.CharField(default='Оставить заявку', max_length=50)),
                ('right_colon_text', models.CharField(blank=True, default='Zanechajte žiadosť', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Naše služby', max_length=255)),
                ('description', models.TextField(blank=True, default='Kancelárske priestory, právne adresy a billboardy – všetko na jednom mieste.', null=True)),
                ('icon_svg', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('office', 'Kancelária'), ('address', 'Sídlo firmy'), ('billboard', 'Billboard')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
