# Generated by Django 5.2 on 2025-10-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
