# Generated by Django 5.2 on 2025-10-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdealitem',
            name='color_theme',
            field=models.CharField(blank=True, default='bg-red-500', help_text="Цветовая тема для оформления карточки (например, 'red', 'blue', 'green')", max_length=20, null=True),
        ),
    ]
