# Generated by Django 5.2 on 2025-10-27 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Hot Deals', max_length=255)),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hot Deal Section',
                'verbose_name_plural': 'Hot Deal Sections',
            },
        ),
        migrations.AlterModelOptions(
            name='hotdealitem',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='color_theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
