# Generated by Django 5.2 on 2025-12-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='key',
        ),
    ]
