# Generated by Django 5.2 on 2025-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='button_text',
            field=models.CharField(blank=True, default='Zanechajte žiadosť', max_length=255, null=True),
        ),
    ]
