# Generated by Django 5.2 on 2025-10-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdealitem',
            name='icon',
        ),
        migrations.DeleteModel(
            name='HotDealSection',
        ),
        migrations.DeleteModel(
            name='HotDealItem',
        ),
    ]
