# Generated by Django 5.2 on 2025-10-27 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0002_hotdealsection_alter_hotdealitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('svg_inline', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('css_class', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csm.icon'),
        ),
    ]
