# Generated by Django 5.2 on 2025-05-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0002_alter_herosection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='right_colon_text',
            field=models.CharField(blank=True, default='Zanechajte žiadosť', max_length=50, null=True),
        ),
    ]
