# Generated by Django 5.2 on 2025-10-22 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0002_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealSectionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_title', models.CharField(default='Horúce ponuky', max_length=255)),
                ('section_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_circle_text', models.CharField(default='Zľava', max_length=50)),
                ('sale_circle_percent', models.IntegerField(default=20)),
                ('title', models.CharField(default='Kancelárske priestory na prenájom', max_length=255)),
                ('description', models.TextField(blank=True, default='Objavte naše exkluzívne kancelárske priestory na prenájom v srdci mesta. Moderné vybavenie, flexibilné možnosti prenájmu a výhodná lokalita – všetko na jednom mieste.', null=True)),
                ('old_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, default=400.0, max_digits=10)),
                ('additional_description', models.TextField(blank=True, default='Získajte profesionálny priestor pre vaše podnikanie za zvýhodnenú cenu. Kontaktujte nás ešte dnes a využite túto jedinečnú ponuku!', null=True)),
                ('advertising_offer_1', models.TextField(blank=True, default='Získajte exkluzívnu reklamnú ponuku na naše kancelárske priestory!', null=True)),
                ('advertising_offer_2', models.TextField(blank=True, default='Profesionálny priestor pre vaše podnikanie za zvýhodnenú cenu.', null=True)),
                ('advertising_offer_3', models.TextField(blank=True, default='Kontaktujte nás ešte dnes a využite túto jedinečnú ponuku!', null=True)),
                ('advertising_offer_4', models.TextField(blank=True, default='Flexibilné možnosti prenájmu v srdci mesta.', null=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('button_text', models.CharField(default='Zanechajte žiadosť', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
