# Generated by Django 5.2 on 2025-10-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0003_alter_hotdealitem_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdealitem',
            name='color_theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
