# Generated by Django 5.2 on 2025-06-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0003_herosection_right_colon_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100, unique=True)),
                ('primary_color', models.CharField(default='#7e22ce', max_length=7)),
                ('secondary_color', models.CharField(default='#1f2937', max_length=7)),
                ('background_color', models.CharField(default='#111827', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Theme',
                'verbose_name_plural': 'Site Themes',
            },
        ),
    ]
