# Generated by Django 5.2 on 2025-06-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0004_sitetheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetheme',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='border_color',
            field=models.CharField(blank=True, default='#374151', max_length=20),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='muted_text_color',
            field=models.CharField(blank=True, default='#9ca3af', max_length=20),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='primary_hover',
            field=models.CharField(default='#6b21a8', max_length=20),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='secondary_hover',
            field=models.CharField(default='#374151', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='background_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='name',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_color',
            field=models.CharField(default='#7e22ce', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='secondary_color',
            field=models.CharField(default='#1f2937', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
