# Generated by Django 5.2 on 2025-06-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0005_remove_sitetheme_updated_at_sitetheme_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='secondary_background_color',
            field=models.CharField(blank=True, default='#f3f4f6', max_length=20),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='secondary_text_color',
            field=models.CharField(blank=True, default='#111827', max_length=20),
        ),
    ]
