# Generated by Django 5.2 on 2025-06-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0006_sitetheme_secondary_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('navbar_background', models.CharField(default='#ffffff', max_length=20)),
                ('body_background', models.CharField(default='#f9fafb', max_length=20)),
                ('footer_background', models.CharField(default='#f1f5f9', max_length=20)),
                ('text_color', models.CharField(default='#111827', max_length=20)),
                ('text_hover_color', models.CharField(default='#1e40af', max_length=20)),
                ('border_color', models.CharField(default='#d1d5db', max_length=20)),
                ('border_hover_color', models.CharField(default='#9ca3af', max_length=20)),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('primary_hover_color', models.CharField(default='#1d4ed8', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
