# Generated by Django 5.2 on 2025-07-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0007_frontendtheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteTheme',
        ),
    ]
