# Generated by Django 5.2 on 2025-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0007_frontendtheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Naše služby', max_length=100)),
                ('description', models.TextField(blank=True, default='Kancelárske priestory, právne adresy a billboardy – všetko na jednom mieste.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteTheme',
        ),
    ]
