# Generated by Django 5.2 on 2025-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(help_text='SMTP server address', max_length=255)),
                ('email_port', models.PositiveIntegerField(help_text='SMTP server port')),
                ('email_host_user', models.EmailField(help_text='SMTP server username', max_length=254)),
                ('email_host_password', models.CharField(help_text='SMTP server password', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS for email connection')),
                ('use_ssl', models.BooleanField(blank=True, default=False, help_text='Use SSL for email connection', null=True)),
                ('gdpr_compliant', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
