# Generated by Django 5.2 on 2025-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='use_ssl',
            field=models.BooleanField(blank=True, default=False, help_text='Use SSL for email connection', null=True),
        ),
    ]
