# Generated by Django 5.2 on 2025-11-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ico', models.CharField(blank=True, max_length=20, verbose_name='IČO')),
                ('dic', models.CharField(blank=True, max_length=20, verbose_name='DIČ')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informácie o firme',
                'verbose_name_plural': 'Informácie o firme',
                'db_table': 'csm_companyinfo',
            },
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='Agentúra Závodský', max_length=100)),
                ('about_description', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer_info', to='company.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Настройки подвала',
                'verbose_name_plural': 'Настройки подвала',
                'db_table': 'csm_footerinfo',
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='company.companyinfo')),
            ],
            options={
                'verbose_name': 'Интервал работы',
                'verbose_name_plural': 'График по дням',
                'db_table': 'csm_openinghour',
                'ordering': ('weekday', 'start_time', 'id'),
                'constraints': [models.UniqueConstraint(fields=('company', 'weekday', 'start_time', 'end_time'), name='uniq_opening_hour')],
            },
        ),
        migrations.CreateModel(
            name='SpecialOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Конкретная дата исключения')),
                ('is_closed', models.BooleanField(default=False, help_text='Закрыто весь день')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_openings', to='company.companyinfo')),
            ],
            options={
                'verbose_name': 'Исключение (праздник/особый день)',
                'verbose_name_plural': 'Исключения по датам',
                'db_table': 'csm_specialopening',
                'ordering': ('date', 'start_time', 'id'),
                'constraints': [models.UniqueConstraint(fields=('company', 'date', 'start_time', 'end_time', 'is_closed'), name='uniq_special_opening')],
            },
        ),
    ]
