# Generated by Django 5.2 on 2025-11-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='x_url',
            field=models.URLField(blank=True, default='x.com', null=True),
        ),
    ]
