# Generated by Django 5.2 on 2025-11-10 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_page', to='company.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': "Страница 'О нас'",
                'verbose_name_plural': "Страницы 'О нас'",
                'db_table': 'csm_aboutuspage',
            },
        ),
    ]
