# Generated by Django 5.2 on 2025-11-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': 'footer settings', 'verbose_name_plural': 'footer settings'},
        ),
        migrations.AddField(
            model_name='openinghour',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Zakázané v tento deň'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer_info', to='company.companyinfo', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Ponedelok'), (1, 'Utorok'), (2, 'Streda'), (3, 'Četvrtok'), (4, 'Piatok'), (5, 'Sobota'), (6, 'Nedeľa')]),
        ),
        migrations.AlterField(
            model_name='specialopening',
            name='date',
            field=models.DateField(help_text='Konkrétny dátum výnimky'),
        ),
        migrations.AlterField(
            model_name='specialopening',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Zakázané v tento deň'),
        ),
    ]
