# Generated by Django 5.2 on 2025-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_footerinfo_options_openinghour_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghour',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
