# Generated by Django 5.2 on 2025-10-31 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('csm', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HotDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('additional_description', models.TextField(blank=True)),
                ('promo_1', models.TextField(blank=True, null=True)),
                ('promo_2', models.TextField(blank=True, null=True)),
                ('promo_3', models.TextField(blank=True, null=True)),
                ('promo_4', models.TextField(blank=True, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('badge_percent', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('button_text', models.CharField(default='Zanechajte žiadosť', max_length=50)),
                ('color_theme', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hot_deal_items', to='accounting.company')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csm.icon')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_deal_items', to='properties.property')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotdeal.hotdealsection')),
            ],
            options={
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('property', 'company'), name='uniq_hotdeal_per_property_per_company'), models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('property',), name='uniq_hotdeal_property_global')],
            },
        ),
    ]
