# Generated by Django 5.2 on 2025-11-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('csm', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('additional_description', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HotDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('additional_description', models.TextField(blank=True, default='')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_1', models.CharField(blank=True, max_length=255)),
                ('promo_2', models.CharField(blank=True, max_length=255)),
                ('promo_3', models.CharField(blank=True, max_length=255)),
                ('promo_4', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('color_theme', models.CharField(blank=True, max_length=50)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('badge_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.company')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotdeal_items', to='csm.icon')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotdeal.hotdealsection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('section', 'property', 'company'), name='uniq_hotdeal_per_section_property_company')],
            },
        ),
    ]
