# Generated by Django 5.2 on 2025-10-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('hotdeal', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotdealitem',
            options={'ordering': ('section', 'property', 'id')},
        ),
        migrations.RemoveConstraint(
            model_name='hotdealitem',
            name='uniq_hotdeal_per_property_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='hotdealitem',
            name='uniq_hotdeal_property_global',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='additional_description',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='badge_percent',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='color_theme',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='date_expiry',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='promo_1',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='promo_2',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='promo_3',
        ),
        migrations.RemoveField(
            model_name='hotdealitem',
            name='promo_4',
        ),
        migrations.AlterField(
            model_name='hotdealitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.company'),
        ),
        migrations.AlterField(
            model_name='hotdealitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='hotdealitem',
            constraint=models.UniqueConstraint(fields=('section', 'property', 'company'), name='uniq_hotdeal_per_section_property_company'),
        ),
        migrations.AddConstraint(
            model_name='hotdealitem',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('section', 'property'), name='uniq_hotdeal_section_property_global'),
        ),
    ]
