# Generated by Django 5.2 on 2025-10-30 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0002_remove_hotdealitem_icon_delete_hotdealsection_and_more'),
        ('hotdeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdealitem',
            name='description',
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='additional_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='button_text',
            field=models.CharField(default='Zanechajte žiadosť', max_length=50),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='color_theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='date_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csm.icon'),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='promo_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='promo_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='promo_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='promo_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
