# Generated by Django 5.2 on 2025-11-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdealitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
