# Generated by Django 5.2 on 2025-10-31 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeal', '0002_alter_hotdealitem_options_and_more'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotdealitem',
            options={},
        ),
        migrations.AlterField(
            model_name='hotdealitem',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='hotdealitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotdeal.hotdealsection'),
        ),
    ]
