# Generated by Django 5.2 on 2025-10-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeal', '0002_remove_hotdealitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotdealitem',
            old_name='additional_description',
            new_name='description',
        ),
    ]
