# Generated by Django 5.2 on 2025-10-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeal', '0003_rename_additional_description_hotdealitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotdealitem',
            old_name='description',
            new_name='additional_description',
        ),
    ]
