# Generated by Django 5.2 on 2025-10-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeal', '0003_alter_hotdealitem_options_alter_hotdealitem_property_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hotdealitem',
            name='uniq_hotdeal_section_property_global',
        ),
    ]
