# Generated by Django 5.2 on 2025-10-31 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('csm', '0001_initial'),
        ('hotdeal', '0004_remove_hotdealitem_uniq_hotdeal_section_property_global'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotdealitem',
            options={'ordering': ['section__order', 'id']},
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='additional_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='badge_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='badge_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='color_theme',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='date_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotdeal_items', to='csm.icon'),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='promo_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='promo_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='promo_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='promo_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='hotdealitem',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('section', 'property'), name='uniq_hotdeal_section_property_global'),
        ),
    ]
