# Generated by Django 5.2 on 2025-10-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeal', '0005_alter_hotdealitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotdealitem',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='hotdealitem',
            name='uniq_hotdeal_section_property_global',
        ),
    ]
