# Generated by Django 5.2 on 2025-10-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeal', '0006_alter_hotdealitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdealitem',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotdealitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
