# Generated by Django 5.2 on 2025-05-07 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaladdressorder',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaladdressorder',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='legaladdressorder',
            name='address_choice',
            field=models.CharField(choices=[('nitra', 'Nitra'), ('bratislava', 'Bratislava')], max_length=50),
        ),
    ]
